import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Banners from "@/components/Banners";
import Footers from "@/components/Footers";
import Nav from "@/components/Nav";
import AdBanner from "@/components/AdBanner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MMO Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      {/* You can add meta tags, title, etc. */}
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>MMO</title>
    </head>
    <body>
    <Banners />
    <Nav/>
    <div className="page-container">
    <AdBanner position="left" /> 
    {children}
    <AdBanner position="right" />
    </div>
      <Footers />
    </body>
  </html>
  );
}
